export const Themes = [
    { name: "light-theme", background: "#FFFFFF", foreground: "#333333", accent: "#9ca3af" },
    { name: "dark-theme", background: "#030712", foreground: "#FFFFFF", accent: "#9ca3af" },

    { name: "ocean-blue-theme", background: "#1B3A4B", foreground: "#D9D9D9", accent: "#3C91E6" },
    { name: "solar-flare-theme", background: "#2D1E2F", foreground: "#EBEBEB", accent: "#FF9800" },
    {
        name: "forest-whisper-theme",
        background: "#2B3A32",
        foreground: "#E4E6C3",
        accent: "#A3C66C",
    },
    {
        name: "midnight-glow-theme",
        background: "#1E1E2A",
        foreground: "#FFFFFF",
        accent: "#BB86FC",
    },
    { name: "sunny-sky-theme", background: "#FFFAF0", foreground: "#2C3E50", accent: "#F39C12" },
    { name: "minty-fresh-theme", background: "#2E3440", foreground: "#ECEFF4", accent: "#8FBCBB" },
    { name: "shadow-realm-theme", background: "#121212", foreground: "#EDEDED", accent: "#FF7F50" },
    { name: "desert-sun-theme", background: "#3C2F2F", foreground: "#F8E1B4", accent: "#D2691E" },
    {
        name: "aurora-borealis-theme",
        background: "#131A22",
        foreground: "#B4C7E7",
        accent: "#78C5D6",
    },
    { name: "vintage-rose-theme", background: "#301934", foreground: "#F5C7C7", accent: "#D28C8C" },
    { name: "steel-blue-theme", background: "#243447", foreground: "#BFD7EA", accent: "#2A9DF4" },
    {
        name: "tropical-paradise-theme",
        background: "#192A2F",
        foreground: "#FFF8DC",
        accent: "#00A896",
    },
    { name: "deep-sea-theme", background: "#172A3A", foreground: "#E1F5FE", accent: "#66FCF1" },
    { name: "warm-autumn-theme", background: "#2C1515", foreground: "#FAEBD7", accent: "#CD5C5C" },
    {
        name: "lavender-fields-theme",
        background: "#2A1A2F",
        foreground: "#E6E6FA",
        accent: "#9370DB",
    },
    { name: "cool-slate-theme", background: "#1C1C1C", foreground: "#ECECEC", accent: "#708090" },
    { name: "sand-dunes-theme", background: "#44373A", foreground: "#F5DEB3", accent: "#FFB74D" },
    { name: "polar-night-theme", background: "#1F2933", foreground: "#C5D8FF", accent: "#88BFFF" },
    { name: "crimson-tide-theme", background: "#2E0000", foreground: "#FFDADA", accent: "#FF6F61" },
    {
        name: "twilight-dawn-theme",
        background: "#0D1B2A",
        foreground: "#FFFFFF",
        accent: "#FFBC42",
    },
];
