export const Themes = [
    { name: "Light", background: "#FFFFFF", foreground: "#333333", accent: "#9ca3af" },
    { name: "Dark", background: "#030712", foreground: "#FFFFFF", accent: "#9ca3af" },

    { name: "Ocean Blue", background: "#1B3A4B", foreground: "#D9D9D9", accent: "#3C91E6" },
    { name: "Solar Flare", background: "#2D1E2F", foreground: "#EBEBEB", accent: "#FF9800" },
    {
        name: "Forest Whisper",
        background: "#2B3A32",
        foreground: "#E4E6C3",
        accent: "#A3C66C",
    },
    { name: "Midnight Glow", background: "#1E1E2A", foreground: "#FFFFFF", accent: "#BB86FC" },
    { name: "Sunny Sky", background: "#FFFAF0", foreground: "#2C3E50", accent: "#F39C12" },
    { name: "Minty Fresh", background: "#2E3440", foreground: "#ECEFF4", accent: "#8FBCBB" },
    { name: "Shadow Realm", background: "#121212", foreground: "#EDEDED", accent: "#FF7F50" },
    { name: "Desert Sun", background: "#3C2F2F", foreground: "#F8E1B4", accent: "#D2691E" },
    {
        name: "Aurora Borealis",
        background: "#131A22",
        foreground: "#B4C7E7",
        accent: "#78C5D6",
    },
    { name: "Vintage Rose", background: "#301934", foreground: "#F5C7C7", accent: "#D28C8C" },
    { name: "Steel Blue", background: "#243447", foreground: "#BFD7EA", accent: "#2A9DF4" },
    {
        name: "Tropical Paradise",
        background: "#192A2F",
        foreground: "#FFF8DC",
        accent: "#00A896",
    },
    { name: "Deep Sea", background: "#172A3A", foreground: "#E1F5FE", accent: "#66FCF1" },
    { name: "Warm Autumn", background: "#2C1515", foreground: "#FAEBD7", accent: "#CD5C5C" },
    {
        name: "Lavender Fields",
        background: "#2A1A2F",
        foreground: "#E6E6FA",
        accent: "#9370DB",
    },
    { name: "Cool Slate", background: "#1C1C1C", foreground: "#ECECEC", accent: "#708090" },
    { name: "Sand Dunes", background: "#44373A", foreground: "#F5DEB3", accent: "#FFB74D" },
    { name: "Polar Night", background: "#1F2933", foreground: "#C5D8FF", accent: "#88BFFF" },
    { name: "Crimson Tide", background: "#2E0000", foreground: "#FFDADA", accent: "#FF6F61" },
    { name: "Twilight Dawn", background: "#0D1B2A", foreground: "#FFFFFF", accent: "#FFBC42" },
];
